name: Test
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.outputstep.outputs.test }}
    steps:
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
          arch: x64
      - id: outputstep
        run: |
          julia -e '
            println("hi")
            println("::set-output name::test=hello")
          '
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}}
    