name: Test
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.outputstep.outputs.test }}
    steps:
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
          arch: x64
      - id: outputstep
        run: |
          julia -e '
            println("hi")
            println("""::set-output name=test::"Found 5 new reference images" """)
            println("something else")
          '
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Status update
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test run'
          description: ${{needs.job1.outputs.output1}}
          state: 'failure'
    